### ISSUE TITLE
Move project to GitHub pages

### ISSUE THREAD

**Issue by mcejp** [MadLittleMods/vga-simulator#1]
Hi,
I see that the website has been unreachable for some time.
Have you considered moving the tool to GitHub Pages? I would be happy to help with setting it up.

**Comment by MadLittleMods** [comment]
My personal site has been down for a while (at least SSL wise).

GitHub pages would work fine for this project because it's all client-side. We would just need to move the example `write_log.txt` somewhere. PR welcome 👍

**Comment by mcejp** [comment]
Since the repo is already structured as a website, it is possible to directly enable GH Pages on the master branch:

![image](https://user-images.githubusercontent.com/29300939/170858031-a873e19a-3cb3-4dde-8f55-6ff207cd35d3.png)

Result: https://mcejp.github.io/vga-simulator/

What is then missing is `elab/vga_sim/write_log.txt` (could be simply added to the repo if you still have the file), and I presume your blog also had some CSS styling on it.

**Comment by danialdunson** [comment]
dear god thank you. 

useless garbage below for SEO so that other cs illiterates may find this aswell:
great substitution for http://ericeastwood.com/lab/vga-simulator. i even tried https://web.archive.org/web/20170507181350/http://ericeastwood.com/lab/vga-simulator#0 with no luck.

**Comment by MadLittleMods** [comment]
The VGA simulator project is now available via GitHub pages :rocket: -> https://madlittlemods.github.io/vga-simulator
